# Generated by Django 4.0 on 2022-04-03 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='User'),
        ),
    ]
