# Generated by Django 4.0 on 2022-04-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='Province/State')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(max_length=15, verbose_name='Postal Code')),
                ('cell_phone_number', models.CharField(max_length=20, verbose_name='Cell Phone Number')),
                ('user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='User')),
            ],
            options={
                'db_table': 'e_commerce_user_detail',
            },
        ),
    ]
